import type { Event } from './sample-events'
export const multiDayEvents: Event[] = [
  {
    id: '12',
    title: 'Company Offsite',
    date: '2025-02-18',
    endDate: '2025-02-20',
    startTime: '09:00',
    endTime: '17:00',
    location: 'Mountain Resort',
    description: 'Team building and strategic planning retreat',
    category: 'work',
    color: '#004E89',
    isAllDay: true,
  },
  {
    id: '13',
    title: 'Product Launch Week',
    date: '2025-02-24',
    endDate: '2025-02-26',
    startTime: '08:00',
    endTime: '18:00',
    location: 'HQ and Remote',
    description: 'Product launch campaign and support',
    category: 'work',
    color: '#004E89',
  },
  {
    id: '14',
    title: 'Conference',
    date: '2025-02-15',
    endDate: '2025-02-17',
    startTime: '09:00',
    endTime: '17:00',
    location: 'Convention Center',
    description: 'Annual tech conference and networking',
    category: 'meeting',
    color: '#FF6B35',
  },
]
